name: Update Japan Portfolio Hourly

on:


  workflow_dispatch:
  push:
  schedule:
    - cron: "0 * * * *"  # every hour

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug repo
        run: |
          pwd
          ls -la

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --upgrade pandas yfinance openpyxl

      - name: Run portfolio updater
        run: python updater.py

      - name: Commit and push updated CSVs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add prices_history.csv portfolio_value_history.csv
          git commit -m "Hourly update Japan portfolio" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
